name: paradrop-daemon
version: '0.3.0'
summary: The ParaDrop daemon running at the extreme edge
description: |
  The ParaDrop deamon manages resources in the Wi-Fi routers and provides a virtualized environment for chutes.
  It also expose local environment information for chutes.

grade: devel
confinement: devmode

apps:
  paradrop:
    command: runpd.sh
    daemon: simple
    plugs:
      - network
      - docker

parts:
  glue:
    plugin: dump
    source: wrapper/
    organize:
      runpd.sh: bin/runpd.sh
      env.sh: bin/env.sh

  paradrop:
    plugin: python
    python-version: python2
    source: src
    build-packages:
      - python-dev
    stage-packages:
      - libcurl4-openssl-dev

  pipework:
    plugin: dump
    source: https://github.com/jpetazzo/pipework
    source-type: git
    organize:
      pipework: usr/bin/pipework
    snap:
      - usr/bin/pipework
