name: paradrop-daemon
version: '0.3.0'
summary: The ParaDrop daemon running at the extreme edge
description: |
  The ParaDrop deamon manages resources in the Wi-Fi routers and provides
  a virtualized environment for chutes.
  It also expose local environment information for chutes.

grade: devel
confinement: devmode

apps:
  paradrop:
    command: ./bin/paradrop

parts:
  paradrop:
    plugin: python
    python-version: python2
    source: daemon
    build-packages:
      - python-dev
    stage-packages:
      - libcurl4-openssl-dev
      - docker.io
    after:
      - pdtools

  pdtools:
    plugin: python
    python-version: python2
    source: pdtools
