image: paradrop/paradrop-ci-environment

stages:
  - unit_test

unit_test_job:
  stage: unit_test
  script:
    - pip install -r requirements.txt
    - nosetests --with-coverage --cover-package=paradrop

#build_job:
#  stage: build
#  only:
#    - master
#  when: on_success
#  script:
#    - ./pdbuild.sh build
#  artifacts:
#    paths:
#      - "paradrop/*.snap"
