language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r docs/requirements.txt"
# command to run tests
script: nosetests
notifications:
  email: false
  slack: paradrop:atIom5TrGkzIsHBdTgP5w8Tq