name: paradrop
version: 0.2.0
vendor: Paradrop Labs <info@paradrop.io>
type: framework
frameworks: 
    - docker

services:
 - name: pd
   start: bin/runpd
   description: Paradrop main daemon
   bus-name: com.paradrop.config
   security-policy:
      apparmor: meta/pd.apparmor
      seccomp: meta/pd.seccomp
