name: paradrop
version: 0.1.0
vendor: Paradrop Labs <snappy-devel@lists.ubuntu.com>
icon: meta/hello.png
type: framework
frameworks: 
    - docker
# binaries:
#  - name: bin/echo
#    caps: []
services:
 - name: pd
   start: bin/pd
   description: Paradrop main daemon
   security-policy:
      apparmor: meta/pd.apparmor
      seccomp: meta/pd.seccomp
