name: paradrop
version: 0.1.0
vendor: Paradrop Labs <snappy-devel@lists.ubuntu.com>
icon: meta/hello.png
type: framework
frameworks: 
    - docker

# binaries:
#  - name: bin/pd
#    security-policy:
#       apparmor: meta/pd.apparmor
#       seccomp: meta/pd.seccomp

binaries:
 - name: bin/dnsmasq
   description: DHCP server
   security-policy:
       apparmor: meta/dnsmasq.apparmor
       seccomp: meta/dnsmasq.seccomp

services:
 - name: pd
   start: bin/pd
   description: Paradrop main daemon
   security-policy:
      apparmor: meta/pd.apparmor
      seccomp: meta/pd.seccomp
# - name: pdconfd
#   start: bin/pd --config
#   description: Paradrop configuration daemon
#   bus-name: com.paradrop.config
#   security-policy:
#      apparmor: meta/pdconfd.apparmor
#      seccomp: meta/pdconfd.seccomp

