name: paradrop
version: 0.1.0
vendor: Paradrop Labs <snappy-devel@lists.ubuntu.com>
icon: meta/hello.png
type: framework
frameworks: 
    - docker

services:
 - name: pd
   start: bin/runpd
   description: Paradrop main daemon
   bus-name: com.paradrop.config
   security-policy:
      apparmor: meta/pd.apparmor
      seccomp: meta/pd.seccomp
