name: paradrop
version: 0.0.1
vendor: Paradrop Labs <snappy-devel@lists.ubuntu.com>
icon: meta/hello.png
binaries:
 - name: bin/start
   caps: 
    - networking
    - network-service
services:
 - name: pserver
   start: bin/paradrop.start
   description: A fun webserver
   caps:
   - networking
   - network-service

# services:
#   - name: paradrop
#     description: Paradrop service
#     start: bin/paradrop.start
#     stop: bin/paradrop.stop
#     security-policy:
#       apparmor: meta/paradrop.apparmor
#       seccomp: meta/paradrop.seccomp