name: paradrop
version: 0.0.1
vendor: Paradrop Labs <snappy-devel@lists.ubuntu.com>
icon: meta/hello.png
# binaries:
#  - name: bin/pd.pex
#    security-policy:
#       apparmor: meta/pd.apparmor
#       seccomp: meta/pd.seccomp
services:
 - name: bin/pd.pex
   start: bin/pd.pex
   description: Paradrop main daemon
   caps:
   - networking
   - network-service

# services:
#   - name: paradrop
#     description: Paradrop service
#     start: bin/paradrop.start
#     stop: bin/paradrop.stop
#     security-policy:
#       apparmor: meta/paradrop.apparmor
#       seccomp: meta/paradrop.seccomp