name: paradrop
version: 0.0.1
vendor: Paradrop Labs <snappy-devel@lists.ubuntu.com>
icon: meta/hello.png
binaries:
 - name: bin/pd.pex
   caps: 
    - networking
    - network-service
# services:
#  - name: bin/pd.pex
#    start: bin/pd.pex
#    description: A fun webserver
#    caps:
#    - networking
#    - network-service

# services:
#   - name: paradrop
#     description: Paradrop service
#     start: bin/paradrop.start
#     stop: bin/paradrop.stop
#     security-policy:
#       apparmor: meta/paradrop.apparmor
#       seccomp: meta/paradrop.seccomp