name: pdinstall
version: 0.2.0
vendor: Paradrop Labs <snappy-devel@lists.ubuntu.com>
type: framework

services:
 - name: pdinstall
   start: bin/runpdinstall
   description: Paradrop installation daemon
   security-policy:
      apparmor: meta/pdinstall.apparmor
      seccomp: meta/pdinstall.seccomp
